### ISSUE TITLE
diod wiki pages from google code?

### ISSUE THREAD

**Issue by lowfatcomputing** [chaos/diod#20]
diod had extensive wiki pages when it was hosted on Google Code. Now these are inaccessible and there is little documentation available.

Could someone who has a copy of them port them over here, maybe to Github pages or this Github wiki?

**Comment by lowfatcomputing** [comment]
http://wiki.diod.googlecode.com/git-history/cab2c7b48cbd58f72e05239115c833e68b38fa84/

**Comment by garlick** [comment]
My intention is to set up gh-pages for this project but I haven't had time yet.  Thanks for opening the issue on it - I should have done that myself.

I did move over the [9P protocol doc](https://github.com/chaos/diod/blob/master/protocol.md).

**Comment by Screwtapello** [comment]
It seems Google Code no longer serves up this historical information.

I don't suppose you made an archive copy?

**Comment by garlick** [comment]
Here's a [tarball](https://drive.google.com/file/d/0B273EWJxZUxsc0xhSFJrYlF5S2M/view?usp=sharing) of diod.wiki, current as of Feb 6 2011.  That's the latest I found at home.  Will see if there is anything newer laying around at work.

**Comment by JamesB192** [comment]
partial from Internet archive at https://github.com/JamesB192/diod/wiki there seems to be an issue with the formatting and links though.

**Comment by garlick** [comment]
I finally moved these pages over to diod's github wiki:

https://github.com/chaos/diod/wiki
