### ISSUE TITLE
disappearing 9p mount - troubleshooting ideas

### ISSUE THREAD

**Issue by borkd** [chaos/diod#42]
I recognize the kernel module is ultimately responsible for the filesystem mount, but can you share a suggested way to troubleshoot client issues, where diodmount/9p mountpoints started to disappear on some machines?

Amount of traffic processed does not seem to play a role here. On some machines things work fine for random amount of time, then all further operations return Input/output error. On others, running the same kernel, the issue is never triggered.

Background:
Recently some of the clients running started loosing mountpoints. I suspect factors external to diod/9p play a role, Meltdown and Spectre mitigation being one, but I'd like to figure out whether others are encountering this issue as well, and if not, the best way to easily reproduce it for kernel folks.

Server: diod server on RH 6.6, built from 1.0.24 release using
   ```./configure --enable-rdmatrans --with-ncurses```

Clients:
- Debian stretch, kernel 4.9.0-6-amd64
- stock diod package provided with stretch (1.0.24-3+b1)
- Infiniband

Timeline:
- diodmount succeeds and 9p mount is established on client
- minutes to hours pass before 9p mount fails
- standalone diodls and diodcat continue to work
- IB fabric passes rudimentary tests between clients where this issue occurred and the corresponding server

Thanks!

**Comment by justcsdr** [comment]
From what I have noted, this appeared after a kernel upgrade. They have changed something in the kernel module.

**Comment by borkd** [comment]
I have updated the original issue with more details. @justcsdr - what kernel ver was broken for you?

**Comment by borkd** [comment]
As I expected the issue was external to diod and 9p which came with the kernel. Packet dumps and wireshark came in handy

**Comment by garlick** [comment]
If you have a moment, it might be nice to give a brief explanation here of what you found out, just in case other people encounter similar problems with symptoms initially pointing to diod/9P.

**Comment by justcsdr** [comment]
Sorry about the confusion (it was a few months ago). Not the mount point disappeared but files. The name of the files was still visible in the directory listing, but the data was not accessible until a re-mount. From what I remember it started around version 4.14 of the Linux kernel. In the meanwhile I have switched off the diod server because I didn't need it any more so I don't know if the problem is still present. There are still a few open bugs for the 9p kernel module from more then an year ago (two of them are opened by me and there are patches to correct them there) but the maintainer is quiet.

**Comment by borkd** [comment]
@garlick - the problem was both trivial and obscure at the same time and would likely not happen in a typical deployment. My systems are stateless and their hostnames and network configuration is auto-generated based on certain set of parameters. Duplicate data in upstream infrastructure led to hash conflicts and thus temporary IP overlaps, BAM. Data validation in semi-autonomous decentralized systems is both essential and tricky.

@justcsdr - Thanks for your response. FWITW - I've been using diod with filesystems with deep and wide directory trees with _lots_ of files, and https://bugzilla.kernel.org/show_bug.cgi?id=195663 never manifested itself. All clients consume 9p mounted data natively rather than via samba reexports.
