### ISSUE TITLE
diod/ops.c:845: undefined reference to `makedev'

### ISSUE THREAD

**Issue by garlick** [chaos/diod#44]
From Hongzhi, Song <hongzhi.song@windriver.com>, reported to v9fs-users:

Error:
diod/ops.c:845: undefined reference to `makedev'

Fixed:
Glibc removes sys/sysmacros.h which defines makedev from sys/types.h since v2.28. [Commit ID: e16deca62e16f]

And then glibc suggestions us to include <sys/sysmacros.h>`directly if code needs it.

```patch
Signed-off-by: Hongzhi.Song <hongzhi.song@windriver.com>
---
 diod/ops.c | 1 +
 1 file changed, 1 insertion(+)

diff --git a/diod/ops.c b/diod/ops.c
index 7812420..28ec80d 100644
--- a/diod/ops.c
+++ b/diod/ops.c
@@ -74,6 +74,7 @@
 #include <pthread.h>
 #include <errno.h>
 #include <sys/types.h>
+#include <sys/sysmacros.h>

 #ifdef __FreeBSD__
 #if !__BSD_VISIBLE
```

**Comment by lfourquaux** [comment]
This has been fixed, hasn't it?  Maybe this issue should be closed?

Note that FreeBSD doesn't have sys/sysmacros.h, so ops.c does not compile any more on FreeBSD.  (I have submitted a pull request with some fixes for FreeBSD.)

**Comment by garlick** [comment]
Closing, fixed I think?  Reopen if not.
