### ISSUE TITLE
Tgetattr/Tsetattr semantics on opened fids

### ISSUE THREAD

**Issue by ebfe** [chaos/diod#47]
It's a bit unclear how Tgetattr/Tsetattr should operate when called with fids that have been opened.
protocol.md says "setattr sets attributes of a file system object referenced by fid". In the case of an already opened fid I would expect that to be the corresponding fd. The code however only operates on the filename f->path (e.g. invoking stat(2) on the path that was used to open the fid). This causes some problems when the client expects the former behaviour (see #19 for example).

Would you be open to changes that switches diod_{get,set}attr to use fstat, fchmod, ftruncate... when called on an opened fid?

**Comment by garlick** [comment]
That would be great.  It would be helpful if this went in with a fairly detailed commit message so we have a good record of why we're doing this.

Extra credit if you can come up with a unit test (and sorry in advance for the state of the test suite).

Thanks!

**Comment by garlick** [comment]
Closing, thanks for the work @ebfe!
