### ISSUE TITLE
Suggestion: use nfs-ganesha-kmod on FreeBSD

### ISSUE THREAD

**Issue by lfourquaux** [chaos/diod#55]
Currently, diod does not support access=user on FreeBSD (cf. np_setfsid in libnpfs/user.c).
It would be nice to use the additional syscalls provided by [nfs-ganesha-kmod](https://github.com/Gandi/nfs-ganesha-kmod) ([in freebsd ports](https://www.freshports.org/net/nfs-ganesha-kmod/)) to implement it.

**Comment by garlick** [comment]
Oh, I was unaware of the work to port ganesha to freebsd.  Thanks for that!  Very interesting!

I've not a lot of time for diod at present, so unfortunately I won't be able to dig into this anytime soon, but it's good to have the issue open in case others are interested or for later when I have time.

**Comment by lfourquaux** [comment]
I had to recompile diod on FreeBSD, so I made a quick attempt to implement it.  I have submitted a pull request if you are interested.

**Comment by lfourquaux** [comment]
How much state is actually shared between the worker threads?  (I don't have a global vision of diod's code.)  Would it be possible to switch to worker processes with some shared memory area?  This would be more portable.

**Comment by garlick** [comment]
That's an interesting idea.  diod was built on top of an existing 9p library, `libnpfs` which implemented the thread pool.  I haven't looked in a while, but certainly the configuration and the cache of passwd/group information is shared.

It would be a big project to do that IMHO.

**Comment by garlick** [comment]
Can I ask what is your use case for diod on FreeBSD?

Integration with FreeNAS would be cool!

**Comment by lfourquaux** [comment]
Unfortunately, my use case is only my home-built NAS, I don't have any connection to FreeNAS (nor do I have the ability to tackle a large rewrite of libnpfs).  But I agree that it would be cool, and I submitted this in the hope that it will eventually be useful to someone else.
