### ISSUE TITLE
review openembedded patch stack for diod

### ISSUE THREAD

**Issue by garlick** [chaos/diod#95]
> Here is the current oe-recepie:
>
> https://github.com/ni/meta-virtualization/tree/nilrt/master/hardknott/recipes-extended/diod
> 
> The patches are in the "files" directory.

_Originally posted by @bjornaxis in https://github.com/chaos/diod/issues/94#issuecomment-1277599896_

**Comment by snogge** [comment]
I submitted [0002-auto.diod.in-remove-bashisms.patch](https://github.com/ni/meta-virtualization/blob/nilrt/master/hardknott/recipes-extended/diod/files/0002-auto.diod.in-remove-bashisms.patch) in #96.

[0001-build-allow-builds-to-work-with-separate-build-dir.patch](https://github.com/ni/meta-virtualization/blob/nilrt/master/hardknott/recipes-extended/diod/files/0001-build-allow-builds-to-work-with-separate-build-dir.patch) was almost completely on master, and the last bits are solved by #97.

[0001-diod-ops.c-add-header-file-for-makedev.patch](https://github.com/ni/meta-virtualization/blob/nilrt/master/hardknott/recipes-extended/diod/files/0001-diod-ops.c-add-header-file-for-makedev.patch) is already on master.

The last remaining patch is [0001-drod-add-option-to-config-systemddir.patch](https://github.com/ni/meta-virtualization/blob/nilrt/master/hardknott/recipes-extended/diod/files/0001-drod-add-option-to-config-systemddir.patch) which adds the possibility to configure systemddir with a `--with-systemddir`.  
I'm not sure that is even needed, it's probably possible to set that on the `make install` commandline. I'll see if I can eliminate it when I see if meta-virtualization wants to update to master of diod. 

Note: The canonical upstream for meta-virtualization is actually https://git.yoctoproject.org/meta-virtualization/

**Comment by snogge** [comment]
The [0001-drod-add-option-to-config-systemddir.patch](https://github.com/ni/meta-virtualization/blob/nilrt/master/hardknott/recipes-extended/diod/files/0001-drod-add-option-to-config-systemddir.patch) is not needed.
`make install systemddir=PATH` does the same thing.

**Comment by snogge** [comment]
All patches in that version of meta-virtualization are now merged or can be discarded. This issue can be closed.

**Comment by garlick** [comment]
Thanks!
