### ISSUE TITLE
diod crashed at shutdown

### ISSUE THREAD

**Issue by bjornaxis** [chaos/diod#99]
Diod crashes sometimes during shutdown. The cause is different, sometimes it is an assert that is hit and sometimes it is a normal segfault.

The probability for crashing is much higher if diod has open connections accessing files when the shutdown is initiated.

The main cause of this crash is that all the connection threads are detached and not actively shut down from the main thread. When main thread exits it will deallocate all its data structures, and if one of the connection threads are still doing some processing it might access this data after this and thus cause the crash.

The deallocation is done by these lines in diod/diod.c:
    diod_fini (ss.srv);
    np_srv_destroy (ss.srv);

**Comment by garlick** [comment]
Closed by #98
